name: dotNet

on:
  push:
    branches:
      - master
      - develop 
      - feature/ci
  pull_request:
    branches:
      - master
      - develop 
      - feature/ci

jobs:

  build-debug:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: [6.x, 7.x]
    
    defaults:
      run:
        working-directory: ./src
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotNET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c debug
  
  test-debug:
    
    needs: build-debug
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        dotnet-version: [6.x, 7.x]
    
    defaults:
      run:
        working-directory: ./src
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotNET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Debug
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  build-and-test-release:
    
    needs: [build-debug, test-debug]
    
    defaults:
      run:
        working-directory: ./src
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup dotNET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal
  
  publish-nuget:
  
    needs: [build-and-test-release]
    
    defaults:
      run:
        working-directory: ./src
  
    runs-on: ubuntu-latest
    
    steps:
      - name: Publish the package to nuget.org
        run: |
          ls -la
          cd jjm.one.Serilog.Extensions.Logging.Helpers
          ls -la
      #run: dotnet nuget push */bin/Release/*.nupkg -k $NUGET_AUTH_TOKEN -s https://api.nuget.org/v3/index.json
      #env:
      #  NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

  deploy-doc:
  
    needs: [build-debug, test-debug]
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Deploy documentation
        run: echo "Deploy documentation"
  
  

  
